version: '3.8'

services:

  postgres-test:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=cdrrmodb_test
      - POSTGRES_USER=jay
      - POSTGRES_PASSWORD=jay123
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    networks:
      - cdrrmo-test
    restart: always

  cdrrmo-server-test:
    image: cdrrmo/cdrrmo-server-test:latest
    build:
      context: ./cdrrmo-api
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - postgres-test
    environment:
      - DATABASE_URL=postgres://jay:jay123@postgres-test:5432/cdrrmodb_test
      # NODE_ENV: test
      - PORT=3000
    networks:
      - cdrrmo-test
    # restart: always

  cdrrmo-client-test:
    image: cdrrmo/cdrrmo-client-test:latest
    build:
      context: ./cdrrmo-client
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    # environment:
      # NODE_ENV: test
      # - VITE_API_URL=http://192.168.1.9:3001
    networks:
      - cdrrmo-test
    # restart: always

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cdrrmo-client-test
      - cdrrmo-server-test
    networks:
      - cdrrmo-test
    # restart: always

networks:
  cdrrmo-test:
    driver: bridge

volumes:
  postgres-test-data:
